services:
  # This is our PostgreSQL Database
  - type: psql
    name: fixmap-db
    databaseName: fixmap_db
    user: fixmap_user
    plan: free

  # This is our Node.js Web Server
  - type: web
    name: fixmap-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fixmap-db
          property: connectionString
      - key: JWT_SECRET
        value: 2d8A7Gsek93mANZyLC4u4GfeV6bDHDBrdHLDfugK1Hv4kUNoDbhdAhbnJPnQ8E3T # <-- PASTE YOUR SECRET KEY HERE
